### ISSUE TITLE
Declare graphvis dependency

### ISSUE THREAD

**Issue by will-ob** [greglook/lein-hiera#3]
Might be helpful to call out the dependency on graphvis explicitly. Rhizome's got it listed, so it would be easy to just reference that. Without graphvis installed, the error spit out is

> java.io.IOException: Cannot run program "dot": error=2, No such file or directory
 at java.lang.ProcessBuilder.start (ProcessBuilder.java:1047)

Not a terribly helpful error message on graphvis' part.

Great plugin, though -- thanks! :)

**Comment by greglook** [comment]
Ah, thanks - always happy to improve the docs! Glad you find it useful.

**Comment by will-ob** [comment]
:+1:
Fast on the draw too :D

**Comment by greglook** [comment]
Added in 300dd6a64408d212e454ea44f632b5976ccb7304.

**Comment by will-ob** [comment]
:+1: :+1: :+1:
